# Generated by Django 5.2.7 on 2025-11-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_task_status_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('yangi', 'yangi'), ('jarayonda', 'jarayonda'), ('bajarildi', 'bajarildi')], default='y', max_length=30),
        ),
    ]
